### ISSUE TITLE
.scrollVertical and .scrollHorizontal are reset after setting .scroll to false

### ISSUE THREAD

**Issue by mrrocks** [koenbok/Framer#220] opened 2015-05-25 02:41 UTC

**Comment by nvh** [comment] 2016-08-03 13:15
This is actually intended behaviour. Setting scroll to false is [literally  the same as setting `scrollHorizontal` and `scrollVertical` to false](https://github.com/koenbok/Framer/blob/master/framer/Components/ScrollComponent.coffee#L176)

What were your trying to achieve when you encountered this?

I'm going to close this, but feel free to keep commenting or open a new issue if you want to discuss this further.

**Closed by nvh** 2016-08-03 13:15 UTC

**Comment by mrrocks** [comment] 2016-08-03 23:24
I understand.

I thought setting the scroll property to true/false was a way to temporarily disabled/enable the scrollComponent. I would never expected having the properties I set when the component is created reseted just by changing one property later.

This kind of looked like a bug to me: http://share.framerjs.com/juhq8ibmuusd/
