### ISSUE TITLE
Share links have init.js not found error

### ISSUE THREAD

**Issue by jdsimcoe** [koenbok/Framer#318] opened 2016-02-27 19:31 UTC
http://share.framerjs.com/qx2or471mscb/

Here is the error thrown on the page:

```log
Failed to load resource: the server responded with a status of 404 (Not Found)
http://share.framerjs.com/qx2or471mscb/framer/init.js
```

**Comment by eelco** [comment] 2016-02-27 23:11
This can happen when sharing an old(er) Framer Studio document with a new version of Framer. Not a bug in Framer but in Framer Studio, so closing it here. Thanks for the report!

**Closed by eelco** 2016-02-27 23:11 UTC
