### ISSUE TITLE
Add customized icon for Framer project folders

### ISSUE THREAD

**Issue by nlevin** [koenbok/Framer#213] opened 2015-05-06 13:30 UTC
Would be great to have ;-)

![folder](https://cloud.githubusercontent.com/assets/158677/7493911/bd17c8a6-f404-11e4-9350-6884fe11fa46.png)

**Comment by cemre** [comment] 2015-05-06 15:43
What do we think about double clicking these opening framer?

**Comment by koenbok** [comment] 2015-05-06 15:53
We can but it's either 1) a folder or 2) an application bundle. By design, double clicking a folder always opens them in the Finder. If you make it an app bundle it opens in Framer but then to look inside the bundle you need to do right-click -> show package contents.

We decided to keep it folders because they're just html projects and people like poking around :-)

**Comment by koenbok** [comment] 2015-05-06 15:53
Fixed in koenbok/FramerStudio/08d7b09a0f60502d33d8ed92c569f296b55007e2

**Closed** 2015-05-06 15:54 UTC
