### ISSUE TITLE
`Event.ImageLoaded` event never triggered in FramerJS?

### ISSUE THREAD

**Issue by hanfeisun** [koenbok/Framer#236] opened 2015-08-03 06:26 UTC
Here is my code, which can be pasted into Framer Studio directly:

    layerA = new Layer()
    
    
    # Listen to the loading event
    layerA.on Events.ImageLoaded, -> 
        print "the image is loaded"
    
    layerA.on Events.ImageLoadError, 
        -> print "the image could not be loaded"
        
    layerA.image = "http://framerjs.com/static/images/home/app-icon.png"
    

However, I found the `the image is loaded` string is never printed.. Is it caused by cache? Or is it a bug.. How can I trigger the Events.ImageLoaded after an image is loaded?

**Comment by jchavarri** [comment] 2015-08-11 15:45
I think this is a duplicate of #190

**Comment by jchavarri** [comment] 2016-01-16 18:21
@koenbok I guess this one can be closed as well.

**Closed** 2016-08-01 23:31 UTC
