### ISSUE TITLE
Animating during drag doesn't stop drag movement

### ISSUE THREAD

**Issue by cleercode** [koenbok/Framer#430] opened 2016-10-01 00:21 UTC
Example code:

```
layer = new Layer
layer.draggable.enabled = true
layer.onDragEnd ->
    layer.animate properties: x: 500
```

In previous versions of Framer, the `x` drag movement would stop when that `layer.animate` call happens. `x` would animate to 500 and `y` would continue animating based on the drag.

This seems to have been changed with the [New animation API](https://github.com/koenbok/Framer/wiki/New-Animation-API). Now, the layer stutters, seemingly because the `x` movement of the drag continues to be applied despite the `layer.animate` call.

Which is a surprising change, but fine. Except:
1. How do I replicate the same effect as the previous version? I could call `layer.animateStop` before `layer.animate`, but that would cancel the `y` movement of the drag as well.
2. This seems to contradict this line in the docs:
   
   > If there is currently an animation on the layer, it gets stopped if it is animating the same properties as the new animation. Simply put, no two animations can be ran on width at the same time, but you can have two separate animations, one running on width and the other on height

**Comment by nvh** [comment] 2016-10-03 12:06
This definitely isn't a new feature of the new animation API, but a regression that should be fixed. Thanks for reporting!

**Comment by nvh** [comment] 2016-12-06 14:19
This has since been fixed!

**Closed by nvh** 2016-12-06 14:19 UTC
Labels: bug
